AllCops:
  Include:
    - "**/*.gemspec"
    - "**/Rakefile"
    - "**/Gemfile"
    - "**/Vagrantfile"
    - "**/config.ru"
  Exclude:
    - "vendor/**/*"
    - "db/schema.rb"

Layout/AlignHash:
  EnforcedLastArgumentHashStyle: ignore_implicit

Metrics/BlockNesting:
  Enabled: false

Layout/CaseIndentation:
  IndentOneStep: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/GuardClause:
  Enabled: false

Layout/IndentHash:
  EnforcedStyle: consistent

Style/LambdaCall:
  EnforcedStyle: call

Metrics/LineLength:
  Max: 120

Style/NonNilCheck:
  IncludeSemanticChanges: true

Metrics/MethodLength:
  Enabled: false

Naming/PredicateName:
  NamePrefixBlacklist:
    - is_

Style/RedundantReturn:
  AllowMultipleReturnValues: true

Style/SingleLineBlockParams:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
  
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
